chore: Update dev workflow to include build and publish steps

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -69,3 +69,52 @@ jobs:
       - name: Terraform Validate
         run: terraform validate
         working-directory: ./terraform
+
+  build-publish:
+    runs-on: ubuntu-latest
+    needs:
+      - ci-app
+      - ci-terraform
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Build Image
+        working-directory: ./app
+        run: |
+          docker build -t ${{ env.APP_NAME }}:latest .
+          # docker tag ${{ env.APP_NAME }}:latest ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:latest
+          # docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:latest
+
+      - name: Create ECR if not exists
+        run: |
+          set +e
+          REPO_EXISTS=$(aws ecr describe-repositories --repository-names $REPO_NAME 2>&1)
+
+          if [[ $REPO_EXISTS == *"RepositoryNotFoundException"* ]]; then
+            aws ecr create-repository --repository-name $REPO_NAME
+            test $? -eq 0 || (echo "Failed to create ECR" && exit 1)
+          fi
+
+          set -e
+        env:
+          REPO_NAME: ${{ env.REPO_NAME }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ env.AWS_REGION }}
+
+      - name: Tag Image
+        run: docker tag ${{ env.APP_NAME }}:latest ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${GITHUB_SHA::8}
+        working-directory: ./app
+
+      - name: Push Image
+        run: docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${GITHUB_SHA::8}
+        working-directory: ./app
